# Generated by Django 4.1.13 on 2025-06-03 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsite', '0002_event_image_event_min_price_event_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='seat_number',
            new_name='seat_no',
        ),
        migrations.AddField(
            model_name='ticket',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='ticketsite.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='row',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='ticketsite.ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('available', 'Доступен'), ('sold', 'Продан')], default='available', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
