# Generated by Django 4.1.13 on 2025-05-28 07:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='akexam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=100, verbose_name='Название экзамена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('exam_date', models.DateField(verbose_name='Дата проведения экзамена')),
                ('exam_image', models.ImageField(blank=True, null=True, upload_to='exam_images/', verbose_name='Изображение задания')),
                ('is_public', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('assigned_users', models.ManyToManyField(related_name='assigned_exams', to=settings.AUTH_USER_MODEL, verbose_name='Назначенные пользователи')),
            ],
            options={
                'verbose_name': 'Экзамен',
                'verbose_name_plural': 'Экзамены',
            },
        ),
    ]
